config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', as: 'new_task'
  post '/tasks', to: 'tasks#create'
  put '/tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update'
  get '/tasks/:id/edit', to: 'tasks#edit'
  delete 'tasks/:id', to: 'tasks#destroy', as: 'destroy_task'
  get '/tasks/:id', to: 'tasks#show', as: 'task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      @task.save
      redirect_to task_path(@task)
    else
      redirect_to new_task
    end
  end

  def edit
  end

  def update
    @task.update(task_params)

    if @task.persisted?
      redirect_to task_path(@task)
    else
      redirect_to edit_task_path(@task)
    end
  end

  def destroy
    if @task.delete
      @task.delete

      redirect_to tasks_path
    else
      redirect_to task_path(@task)
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row m-3">
        <div class="col-12">
          <%= yield %>
        </div>
      </div>
    
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :details %>
    <%= form.text_area :details, class: 'form-control' %>
  </div>
  <div class="form-group">
    <% unless @task.new_record? %>
      <%= form.check_box :completed, class: 'form-check-input' %>
      <%= form.label :completed, class: 'form-check-label' %>
    <% end %>
  </div>
  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
   <div class="col-12">
    <h1>Edit task</h1>

    <%= render 'form' %>

    <%= link_to 'Back to the task', task_path(@task), class: 'btn btn-secondary mt-3'%>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul class="tasks">
  <% @tasks.each do |task| %>
    <li>
      <div class="task-detail">
        <input type="checkbox" <%= 'checked' if task.completed == true %> disabled>
        <%= link_to task.title, task_path(task) %>
        <%= link_to destroy_task_path(task), method: 'delete' do  %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

<%= link_to 'New task', new_task_path, class: 'btn btn-primary' %>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= link_to 'Back to the tasks', tasks_path, class: 'btn btn-secondary' %>
      <h1>New task</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<%= link_to 'Edit task', edit_task_path, method: 'put', class: 'btn btn-primary' %>

<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<% if @task.completed %>
<input type="checkbox" checked>
  <p>Task is completed</p>
<% else %>
  <input type="checkbox">
  <p>Task is not done yet</p>
<% end %>

<%= link_to 'Back to list', tasks_path, class: 'btn btn-secondary' %>